#!/bin/bash
set -e
cd review-graph
which cabal-dev || cabal update && cabal install cabal-dev
cabal-dev install

eval "./cabal-dev/bin/review-graph ${NAMES}"

# jenkins saves and serves review-graph.svg

