#!/bin/bash
set -e
cd random-review-circle
which cabal-dev || ( cabal update && cabal install cabal-dev )
cabal-dev install --sandbox=$WORKSPACE/cabal-sandbox

cd $WORKSPACE

eval "./cabal-sandbox/bin/random-review-circle ${NAMES}"

# jenkins saves and serves review-graph.svg
